# Generated by Django 4.2.7 on 2024-01-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='alt_title',
        ),
        migrations.AddField(
            model_name='category',
            name='alt_title1',
            field=models.CharField(default=0, max_length=50, verbose_name='Alt Başlık1'),
        ),
        migrations.AddField(
            model_name='category',
            name='alt_title2',
            field=models.CharField(default=0, max_length=50, verbose_name='Alt Başlık2'),
        ),
        migrations.AddField(
            model_name='category',
            name='alt_title3',
            field=models.CharField(default=0, max_length=50, verbose_name='Alt Başlık3'),
        ),
    ]
