# Generated by Django 4.2.7 on 2024-01-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_remove_category_alt_title_category_alt_title1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='alt_title1',
            field=models.CharField(max_length=50, null=True, verbose_name='Alt Başlık1'),
        ),
        migrations.AlterField(
            model_name='category',
            name='alt_title2',
            field=models.CharField(max_length=50, null=True, verbose_name='Alt Başlık2'),
        ),
        migrations.AlterField(
            model_name='category',
            name='alt_title3',
            field=models.CharField(max_length=50, null=True, verbose_name='Alt Başlık3'),
        ),
    ]
