# Generated by Django 4.2.7 on 2024-01-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_alter_category_alt_title1_alter_category_alt_title2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kurs',
            old_name='img',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='category',
            name='alt_title1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Alt Başlık1'),
        ),
        migrations.AlterField(
            model_name='category',
            name='alt_title2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Alt Başlık2'),
        ),
        migrations.AlterField(
            model_name='category',
            name='alt_title3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Alt Başlık3'),
        ),
    ]
