# Generated by Django 4.2.7 on 2024-01-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0004_rename_img_kurs_image_alter_category_alt_title1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurs',
            name='image',
            field=models.ImageField(upload_to='Kurs', verbose_name='Resim'),
        ),
    ]
