# Generated by Django 4.2.7 on 2024-01-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0009_alter_kurs_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='alt_title4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Alt Başlık4'),
        ),
        migrations.AddField(
            model_name='category',
            name='alt_title5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Alt Başlık5'),
        ),
        migrations.AddField(
            model_name='category',
            name='alt_title6',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Alt Başlık6'),
        ),
    ]
