# Generated by Django 4.2.7 on 2024-01-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0010_category_alt_title4_category_alt_title5_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Başlik')),
                ('Slug', models.SlugField(verbose_name='Slug')),
            ],
        ),
    ]
