# Generated by Django 4.2.7 on 2024-01-02 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0011_maincategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainCategory',
        ),
    ]
