# Generated by Django 4.2.7 on 2024-01-03 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0013_province_kurs_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.province', verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='province',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
