# Generated by Django 4.2.7 on 2024-01-03 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0015_rename_slug_province_islug'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacetoFaceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlik')),
                ('slug', models.SlugField(verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlik')),
                ('slug', models.SlugField(verbose_name='Slug')),
            ],
        ),
        migrations.AlterField(
            model_name='kurs',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.facetofacecategory', verbose_name='Kategori'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
