# Generated by Django 4.2.7 on 2024-01-03 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0018_alter_kurs_facetofacecategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facetofacecategory',
            old_name='slug',
            new_name='tslug',
        ),
        migrations.RenameField(
            model_name='onlinecategory',
            old_name='slug',
            new_name='yslug',
        ),
        migrations.AlterField(
            model_name='kurs',
            name='facetofacecategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.facetofacecategory', verbose_name='Yüz Yüze KAtegori'),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='onlinecategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.onlinecategory', verbose_name='Online Kategori'),
        ),
    ]
