# Generated by Django 4.2.7 on 2024-01-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0019_rename_slug_facetofacecategory_tslug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurs',
            name='text',
            field=models.CharField(default='-', max_length=50, verbose_name='Acıklama'),
        ),
    ]
