# Generated by Django 4.2.7 on 2024-01-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0021_alter_kurs_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurs',
            name='puan',
            field=models.IntegerField(blank=True, default=0, verbose_name='Puan'),
        ),
    ]
