# Generated by Django 4.2.7 on 2024-01-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0022_alter_kurs_puan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurs',
            name='image',
            field=models.ImageField(blank=True, upload_to='kurs', verbose_name='Resim'),
        ),
    ]
