# Generated by Django 4.2.7 on 2024-01-17 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appMy', '0023_alter_kurs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurs',
            name='image',
            field=models.ImageField(upload_to='kurs', verbose_name='Resim'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='Yorum')),
                ('date_now', models.DateTimeField(verbose_name='Tarih ve Saat')),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.kurs', verbose_name='Yorum yapılan Kurs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
