# Generated by Django 4.2.7 on 2024-01-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0025_alter_comment_date_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurs',
            name='commen_num',
            field=models.IntegerField(default=0, verbose_name='Yorum Sayısı'),
        ),
    ]
