# Generated by Django 4.2.7 on 2024-01-17 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appMy', '0027_rename_commen_num_kurs_comment_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurs',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='user2', to=settings.AUTH_USER_MODEL, verbose_name='Begenen Kullanıcılar'),
        ),
    ]
