# Generated by Django 4.2.7 on 2024-01-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0029_alter_kurs_text_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurs',
            name='likes_num',
            field=models.IntegerField(default=0, verbose_name='Begeni Sayısı'),
        ),
    ]
