# Generated by Django 4.2.7 on 2024-01-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0032_kurs_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurs',
            name='likes_num',
        ),
        migrations.RemoveField(
            model_name='kurs',
            name='likes',
        ),
        migrations.AddField(
            model_name='kurs',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Begeni Sayısı'),
        ),
    ]
