# Generated by Django 4.2.7 on 2024-01-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0032_alter_kurs_date_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurs',
            name='date_now',
        ),
        migrations.AddField(
            model_name='kurs',
            name='date',
            field=models.DateTimeField(default='-', verbose_name='Tarih ve Saat'),
        ),
    ]
