# Generated by Django 4.2.7 on 2024-01-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0033_remove_kurs_likes_num_remove_kurs_likes_kurs_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='facetofacecategory',
            name='province_options',
            field=models.ManyToManyField(to='appMy.province', verbose_name='İl Seçenekleri'),
        ),
    ]
