# Generated by Django 4.2.7 on 2024-01-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0035_sepet'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepet',
            name='toplam',
            field=models.FloatField(default=0, verbose_name='Toplam Fiyat'),
        ),
        migrations.AlterField(
            model_name='sepet',
            name='adet',
            field=models.IntegerField(default=0, verbose_name='Adet'),
        ),
    ]
