# Generated by Django 4.2.7 on 2024-01-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0036_sepet_toplam_alter_sepet_adet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurs',
            name='price',
            field=models.FloatField(default=0, verbose_name='Fiyat'),
        ),
    ]
