# Generated by Django 4.2.7 on 2024-01-17 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0037_alter_kurs_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurs',
            name='date',
        ),
    ]
