# Generated by Django 4.2.7 on 2024-01-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0037_alter_kurs_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurs',
            name='first',
            field=models.CharField(default='varsayilan_deger', max_length=255),
        ),
    ]
