# Generated by Django 4.2.7 on 2024-01-22 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0038_kurs_first'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurs',
            name='first',
        ),
    ]
