# Generated by Django 4.2.7 on 2024-01-17 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0041_alter_kurs_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_now',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarih ve Saat'),
        ),
    ]
