# Generated by Django 4.2.7 on 2024-01-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0002_usermy_user_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermy',
            name='profil_image',
            field=models.ImageField(default='-', upload_to='Kurs', verbose_name='Profil Resmi'),
        ),
    ]
