# Generated by Django 4.2.7 on 2024-01-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0005_rename_profil_image_usermy_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermy',
            name='profile_image',
            field=models.ImageField(max_length=200, upload_to='profil', verbose_name='Profil Resmi'),
        ),
    ]
