# Generated by Django 4.2.7 on 2024-01-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0006_alter_usermy_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermy',
            name='profile_image',
            field=models.ImageField(default='appMy/static/image/images.png', max_length=200, upload_to='profil', verbose_name='Profil Resmi'),
        ),
    ]
